-- init.sql

CREATE DATABASE IF NOT EXISTS database;
USE database;



CREATE TABLE IF NOT EXISTS member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nickName VARCHAR(255),
    loginId VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON db.* TO 'admin'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS file (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    content VARCHAR(255),
    language VARCHAR(255),
    create_dt VARCHAR(255),
    update_dt VARCHAR(255),
    PRIMARY KEY (id)
);