spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username : username
    password: password

rabbitmq:
  queue:
    name: java-queue
  exchange:
    name: language-exchange
  routing:
    key : java