apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS db;
    USE db;

    GRANT ALL PRIVILEGES ON db.* TO 'admin'@'%';
    FLUSH PRIVILEGES;

    CREATE TABLE IF NOT EXISTS project (
        project_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        project_pw VARCHAR(255),
        is_locked BOOLEAN NOT NULL DEFAULT FALSE,
        max_user INT,
        language VARCHAR(255),
        is_end BOOLEAN NOT NULL DEFAULT FALSE
    );

    CREATE TABLE IF NOT EXISTS member (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        nickName VARCHAR(255),
        loginId VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS participant (
        participant_id BIGINT AUTO_INCREMENT PRIMARY KEY,
        project_id BIGINT,
        user_id BIGINT,
        permission BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (project_id) REFERENCES project(project_id),
        FOREIGN KEY (user_id) REFERENCES member(id)
    );

    CREATE TABLE IF NOT EXISTS message (
        message_id BIGINT AUTO_INCREMENT PRIMARY KEY,
        project_id BIGINT,
        participant_id BIGINT,
        message VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (project_id) REFERENCES project(project_id) ON DELETE CASCADE,
        FOREIGN KEY (participant_id) REFERENCES participant(participant_id)
    );
